// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.6.1
// source: proto/wishlist.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Llaves      int64 `protobuf:"varint,1,opt,name=Llaves,proto3" json:"Llaves,omitempty"`
	Nronda      int64 `protobuf:"varint,2,opt,name=Nronda,proto3" json:"Nronda,omitempty"`
	TotalRondas int64 `protobuf:"varint,3,opt,name=total_rondas,json=totalRondas,proto3" json:"total_rondas,omitempty"`
}

func (x *MsgReq) Reset() {
	*x = MsgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_wishlist_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgReq) ProtoMessage() {}

func (x *MsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wishlist_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgReq.ProtoReflect.Descriptor instead.
func (*MsgReq) Descriptor() ([]byte, []int) {
	return file_proto_wishlist_proto_rawDescGZIP(), []int{0}
}

func (x *MsgReq) GetLlaves() int64 {
	if x != nil {
		return x.Llaves
	}
	return 0
}

func (x *MsgReq) GetNronda() int64 {
	if x != nil {
		return x.Nronda
	}
	return 0
}

func (x *MsgReq) GetTotalRondas() int64 {
	if x != nil {
		return x.TotalRondas
	}
	return 0
}

type MsgResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Region *Region `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
}

func (x *MsgResp) Reset() {
	*x = MsgResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_wishlist_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgResp) ProtoMessage() {}

func (x *MsgResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wishlist_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgResp.ProtoReflect.Descriptor instead.
func (*MsgResp) Descriptor() ([]byte, []int) {
	return file_proto_wishlist_proto_rawDescGZIP(), []int{1}
}

func (x *MsgResp) GetRegion() *Region {
	if x != nil {
		return x.Region
	}
	return nil
}

type Region struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Region string `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
}

func (x *Region) Reset() {
	*x = Region{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_wishlist_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Region) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Region) ProtoMessage() {}

func (x *Region) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wishlist_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Region.ProtoReflect.Descriptor instead.
func (*Region) Descriptor() ([]byte, []int) {
	return file_proto_wishlist_proto_rawDescGZIP(), []int{2}
}

func (x *Region) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type RespReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Usuariosrestantes int64 `protobuf:"varint,1,opt,name=usuariosrestantes,proto3" json:"usuariosrestantes,omitempty"`
	Llavesentregadas  int64 `protobuf:"varint,2,opt,name=llavesentregadas,proto3" json:"llavesentregadas,omitempty"`
}

func (x *RespReq) Reset() {
	*x = RespReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_wishlist_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespReq) ProtoMessage() {}

func (x *RespReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wishlist_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespReq.ProtoReflect.Descriptor instead.
func (*RespReq) Descriptor() ([]byte, []int) {
	return file_proto_wishlist_proto_rawDescGZIP(), []int{3}
}

func (x *RespReq) GetUsuariosrestantes() int64 {
	if x != nil {
		return x.Usuariosrestantes
	}
	return 0
}

func (x *RespReq) GetLlavesentregadas() int64 {
	if x != nil {
		return x.Llavesentregadas
	}
	return 0
}

type RespResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Usuarios *Faltan `protobuf:"bytes,1,opt,name=usuarios,proto3" json:"usuarios,omitempty"`
}

func (x *RespResp) Reset() {
	*x = RespResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_wishlist_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespResp) ProtoMessage() {}

func (x *RespResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wishlist_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespResp.ProtoReflect.Descriptor instead.
func (*RespResp) Descriptor() ([]byte, []int) {
	return file_proto_wishlist_proto_rawDescGZIP(), []int{4}
}

func (x *RespResp) GetUsuarios() *Faltan {
	if x != nil {
		return x.Usuarios
	}
	return nil
}

type Faltan struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Usuariosrest int64 `protobuf:"varint,1,opt,name=usuariosrest,proto3" json:"usuariosrest,omitempty"`
}

func (x *Faltan) Reset() {
	*x = Faltan{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_wishlist_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Faltan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Faltan) ProtoMessage() {}

func (x *Faltan) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wishlist_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Faltan.ProtoReflect.Descriptor instead.
func (*Faltan) Descriptor() ([]byte, []int) {
	return file_proto_wishlist_proto_rawDescGZIP(), []int{5}
}

func (x *Faltan) GetUsuariosrest() int64 {
	if x != nil {
		return x.Usuariosrest
	}
	return 0
}

var File_proto_wishlist_proto protoreflect.FileDescriptor

var file_proto_wishlist_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x22, 0x5b, 0x0a, 0x06,
	0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x4c, 0x6c, 0x61, 0x76, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x4c, 0x6c, 0x61, 0x76, 0x65, 0x73, 0x12, 0x16,
	0x0a, 0x06, 0x4e, 0x72, 0x6f, 0x6e, 0x64, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x4e, 0x72, 0x6f, 0x6e, 0x64, 0x61, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f,
	0x72, 0x6f, 0x6e, 0x64, 0x61, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x52, 0x6f, 0x6e, 0x64, 0x61, 0x73, 0x22, 0x2f, 0x0a, 0x07, 0x4d, 0x73, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x24, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x67, 0x69,
	0x6f, 0x6e, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x22, 0x20, 0x0a, 0x06, 0x52, 0x65,
	0x67, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x22, 0x63, 0x0a, 0x07,
	0x52, 0x65, 0x73, 0x70, 0x52, 0x65, 0x71, 0x12, 0x2c, 0x0a, 0x11, 0x75, 0x73, 0x75, 0x61, 0x72,
	0x69, 0x6f, 0x73, 0x72, 0x65, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x11, 0x75, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x73, 0x72, 0x65, 0x73, 0x74,
	0x61, 0x6e, 0x74, 0x65, 0x73, 0x12, 0x2a, 0x0a, 0x10, 0x6c, 0x6c, 0x61, 0x76, 0x65, 0x73, 0x65,
	0x6e, 0x74, 0x72, 0x65, 0x67, 0x61, 0x64, 0x61, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x10, 0x6c, 0x6c, 0x61, 0x76, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x72, 0x65, 0x67, 0x61, 0x64, 0x61,
	0x73, 0x22, 0x34, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x52, 0x65, 0x73, 0x70, 0x12, 0x28, 0x0a,
	0x08, 0x75, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x46, 0x61, 0x6c, 0x74, 0x61, 0x6e, 0x52, 0x08, 0x75,
	0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x73, 0x22, 0x2c, 0x0a, 0x06, 0x46, 0x61, 0x6c, 0x74, 0x61,
	0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x75, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x73, 0x72, 0x65, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x75, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f,
	0x73, 0x72, 0x65, 0x73, 0x74, 0x32, 0x62, 0x0a, 0x0e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x24, 0x0a, 0x05, 0x61, 0x76, 0x69, 0x73, 0x6f,
	0x12, 0x0c, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x0d,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2a, 0x0a,
	0x09, 0x72, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x12, 0x0d, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x52, 0x65, 0x73, 0x70, 0x42, 0x08, 0x5a, 0x06, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_wishlist_proto_rawDescOnce sync.Once
	file_proto_wishlist_proto_rawDescData = file_proto_wishlist_proto_rawDesc
)

func file_proto_wishlist_proto_rawDescGZIP() []byte {
	file_proto_wishlist_proto_rawDescOnce.Do(func() {
		file_proto_wishlist_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_wishlist_proto_rawDescData)
	})
	return file_proto_wishlist_proto_rawDescData
}

var file_proto_wishlist_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_wishlist_proto_goTypes = []interface{}{
	(*MsgReq)(nil),   // 0: grpc.MsgReq
	(*MsgResp)(nil),  // 1: grpc.MsgResp
	(*Region)(nil),   // 2: grpc.Region
	(*RespReq)(nil),  // 3: grpc.RespReq
	(*RespResp)(nil), // 4: grpc.RespResp
	(*Faltan)(nil),   // 5: grpc.Faltan
}
var file_proto_wishlist_proto_depIdxs = []int32{
	2, // 0: grpc.MsgResp.region:type_name -> grpc.Region
	5, // 1: grpc.RespResp.usuarios:type_name -> grpc.Faltan
	0, // 2: grpc.MessageService.aviso:input_type -> grpc.MsgReq
	3, // 3: grpc.MessageService.respuesta:input_type -> grpc.RespReq
	1, // 4: grpc.MessageService.aviso:output_type -> grpc.MsgResp
	4, // 5: grpc.MessageService.respuesta:output_type -> grpc.RespResp
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_wishlist_proto_init() }
func file_proto_wishlist_proto_init() {
	if File_proto_wishlist_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_wishlist_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_wishlist_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_wishlist_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Region); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_wishlist_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_wishlist_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_wishlist_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Faltan); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_wishlist_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_wishlist_proto_goTypes,
		DependencyIndexes: file_proto_wishlist_proto_depIdxs,
		MessageInfos:      file_proto_wishlist_proto_msgTypes,
	}.Build()
	File_proto_wishlist_proto = out.File
	file_proto_wishlist_proto_rawDesc = nil
	file_proto_wishlist_proto_goTypes = nil
	file_proto_wishlist_proto_depIdxs = nil
}
